const SITE_DATA = {
  profile: {
    name: "ליה",
    englishName: "Liya",
    handle: "@not.liya",
    instagramUrl: "https://www.instagram.com/not.liya/",
    tiktokUrl: "https://www.tiktok.com/@not.liya",
    artPortrait: "images/art/portrait.jpg",
    artCoffee: "images/art/coffee.jpg",
    artProtein: "images/art/protein.jpg",
    artPencil: "images/art/pencil.jpg",
    artBalcony: "images/art/balcony.jpg",
    artBedrot: "images/art/bedrot.jpg",
    avatar: "images/avatar.jpg",
    creatorNoteHe: "היי ליה 👋 ראיתי ששאלת בסטורי איזה אתר לבנות, וזה נשמע לי כמו פרויקט ממש מעניין אז פשוט ישבתי ובניתי לך אחד. קניתי גם את notliya.com כי חבל שמישהו אחר יקח. אם בא לך עליו – רק תגידי, אני מעביר לך את כל הגישה והניהול באהבה.",
    creatorNoteEn: "Hey Liya 👋 saw your story asking what site to build, and it sounded like such a fun project so I sat down and made one for you. I also grabbed notliya.com so nobody else takes it. If you want it, just let me know and I'll hand over full keys and ownership.",
    bioHe: "פאנצ'ים שיכלתי לזרוק, אהבה שיכלתי לקבל, ושקט נפשי במיטה.",
    bioEn: "Punchlines I could have thrown, love I could have received, and peace of mind in bed.",
    statusHe: "ערה ב-3 בלילה, גוללת במיטה",
    statusEn: "Awake at 3 AM, bed-rotting"
  },

  creatorLetter: {
    author: "לוי",
    authorEn: "Levi",
    titleHe: "היי ליה, זה לוי 👋",
    titleEn: "Hey Liya, it's Levi 👋",
    subtitleHe: "מכתב אישי ממי שבנה לך את האתר",
    subtitleEn: "A personal note from who built your site",
    bodyHe: "ראיתי ששאלת בסטורי איזה אתר לבנות, וזה נשמע לי כמו פרויקט ממש מגניב – אז פשוט ישבתי בסופ״ש ובניתי לך אותו.\n\nקניתי גם את הדומיין notliya.com כדי שאף אחד ברשת לא יחטוף לך אותו.\n\nרציתי שזה ירגיש 100% כמוך: הומור שחור, קפה קר, ואיורים מקוריים שלך במקום סתם אתר תדמית משעמם.\n\nאם אהבת ובא לך את האתר – רק תשלחי לי הודעה באינסטגרם ואני מעביר לך באהבה את כל המפתחות, הניהול והדומיין בלי שום תנאים. תהני!",
    bodyEn: "Saw your story asking what site to build, and it sounded like such a fun project — so I sat down over the weekend and built one for you.\n\nI also bought notliya.com so nobody else takes it.\n\nWanted it to feel 100% like you: dark humor, iced coffee, and original custom artwork rather than a boring corporate template.\n\nIf you like it and want the site — just shoot me a DM on Instagram and I'll gladly hand over full keys, ownership, and the domain with no strings attached. Enjoy!",
    audioSrc: "audio/voice_note.mp3",
    audioDuration: "0:24",
    dmUrl: "https://www.instagram.com/not.liya/"
  },

  themes: [
    {
      id: "emo",
      nameHe: "חדר אימו (ברירת מחדל)",
      nameEn: "Emo Bedroom (Default)",
      descHe: "גרפיט רך, סגול לבנדר מאובק וקרם נעים",
      descEn: "Soft graphite, dusty lilac & warm cream",
      swatch: ["#141316", "#bda0e8", "#f4dfb5"]
    },
    {
      id: "zine",
      nameHe: "זין רטרו (Sepia & Clay)",
      nameEn: "Vintage Zine (Sepia & Clay)",
      descHe: "נייר קפה חמים, טרקוטה כפרית וגווני עיתון",
      descEn: "Warm coffee paper, rustic terracotta & analog zine",
      swatch: ["#191613", "#e07a5f", "#81b29a"]
    },
    {
      id: "matcha",
      nameHe: "מאצ'ה גרנאג' (Moss & Oat)",
      nameEn: "Matcha Grunge (Moss & Oat)",
      descHe: "זית עמוק, ירוק מאצ'ה מרגיע ופשתן",
      descEn: "Deep olive, calming matcha green & linen",
      swatch: ["#121512", "#a7c49d", "#f0ead2"]
    },
    {
      id: "twilight",
      nameHe: "סייבר טוויליט (Y2K Dusk)",
      nameEn: "Cyber Twilight (Y2K Dusk)",
      descHe: "לילה סגלגל עמוק, מנטה פסטל ומג'נטה",
      descEn: "Deep midnight violet, pastel mint & magenta",
      swatch: ["#0e0d18", "#a78bfa", "#6ee7b7"]
    },
    {
      id: "cream-day",
      nameHe: "קרם שיק (Light & Minimal)",
      nameEn: "Cream Chic (Light & Minimal)",
      descHe: "שיבולת שועל, נייר בהיר וטרקוטה חמימה",
      descEn: "Warm oat, bright paper & earthy terracotta",
      swatch: ["#f5f2eb", "#b05d47", "#1c1a17"]
    }
  ],

  artGallery: [
    {
      id: "balcony",
      image: "images/art/balcony.jpg",
      titleHe: "שקיעה בתל אביב עם קפה קר",
      titleEn: "Sunset Balcony in Tel Aviv",
      tagHe: "סגנון אנימה אינדי 🌇",
      tagEn: "Indie Anime 🌇",
      descHe: "סוודר אוברסייז, קפה קר עם קש, ורוח ערב שמנקה את הראש מכל השטויות.",
      descEn: "Oversized knit sweater, iced coffee with a straw, and twilight rooftop peace."
    },
    {
      id: "bedrot",
      image: "images/art/bedrot.jpg",
      titleHe: "בוריטו שמיכות ב-3 בלילה",
      titleEn: "3 AM Burrito Blanket Bedrot",
      tagHe: "הדחקה מקצועית 👻",
      tagEn: "Professional Repression 👻",
      descHe: "עטופה בשמיכה כמו בוריטו, בוהה באור הטלפון לצד רוח רפאים חמודה של חרדה קיומית.",
      descEn: "Swaddled like a burrito, phone light glowing, chatting with the cute existential dread ghost."
    },
    {
      id: "portrait",
      image: "images/art/portrait.jpg",
      titleHe: "הדיוקן האדיש המקורי",
      titleEn: "The Original Deadpan Portrait",
      tagHe: "ציניות טהורה 🎨",
      tagEn: "Pure Deadpan 🎨",
      descHe: "שיער גלי כהה, עגיל ספטום, ומבט שאומר בדיוק מה אני חושבת על המין האנושי.",
      descEn: "Dark wavy locks, silver septum ring, and that signature unbothered side-eye."
    },
    {
      id: "coffee",
      image: "images/art/coffee.jpg",
      titleHe: "אייס קפה והדחקה פעילה",
      titleEn: "Iced Coffee & Radical Peace",
      tagHe: "שקט נפשי ☕",
      tagEn: "Peace of Mind ☕",
      descHe: "הבעיות לא ייעלמו אם תתעלמי מהן, אבל לפחות עם קפה קר יש שקט ומזגן.",
      descEn: "Ignoring your life won't solve it, but at least cold brew tastes divine in bed."
    },
    {
      id: "protein",
      image: "images/art/protein.jpg",
      titleHe: "חלבון ושייקרים מסוכנים",
      titleEn: "Whey Isolate Invasion",
      tagHe: "רוסט על ג'ימברו 🏋️",
      tagEn: "Gym-Bro Roast 🏋️",
      descHe: "החיים עם בן זוג שמודד גרמים של איזולט ב-2 בלילה ושייקרים שמסכנים את שלום הציבור.",
      descEn: "Life in the shadow of lukewarm protein water and biohazard shakers in the sink."
    },
    {
      id: "pencil",
      image: "images/art/pencil.jpg",
      titleHe: "טראומת העט-עיפרון (0.7 מ״מ)",
      titleEn: "The 0.7mm Mechanical Pencil",
      tagHe: "סיפור מקור ✏️",
      tagEn: "Origin Story ✏️",
      descHe: "הילד מכיתה ד' שהפך את המכנסיים שלי למטרה לשפיצים. הטראומה שמימנה אישיות שלמה.",
      descEn: "The 4th grade lead-jabbing incident that forged an elite dark humor shield."
    }
  ],

  stories: [
    {
      id: "bedrot",
      artImage: "images/art/bedrot.jpg",
      realImage: "images/post_4_DcwHOeJiqKg.jpg",
      realLabelHe: "בסרטון המקורי 👻",
      realLabelEn: "Original Video 👻",
      tagHe: "שקט נפשי במיטה",
      tagEn: "Bed-Rotting & Peace",
      titleHe: "בוריטו שמיכות, קפה קר, ואפס רצון לצאת",
      titleEn: "Burrito Blanket, Iced Coffee & Zero Battery",
      descHe: "למחוק את כל הרעש מסביב היה הדבר הכי טוב שעשיתי. להישאר במיטה עטופה כמו בוריטו ב-14:00 ולבהות בתקרה זו לא עצלנות – זה נטו הישרדות. אם מתעלמים מבעיות מספיק זמן הן אולי לא נעלמות, אבל לפחות יש מזגן ושקט.",
      descEn: "Tuning out the global noise was the best move I ever made. Staying in bed swaddled like a burrito staring at the ceiling isn't laziness — it's survival. If you ignore problems they might not vanish, but at least there's air conditioning."
    },
    {
      id: "balcony",
      artImage: "images/art/balcony.jpg",
      realImage: "images/post_6_DR2KOUtAh0b.jpg",
      realLabelHe: "הרנט על החיים 🌇",
      realLabelEn: "Life Rant Reel 🌇",
      tagHe: "שקיעה בתל אביב",
      tagEn: "Sunset Thoughts",
      titleHe: "קפה קר במרפסת: איך שרדנו עד עכשיו?",
      titleEn: "Balcony Cold Brew: How Did We Survive?",
      descHe: "סוודר אוברסייז, קפה קר, ובריזה של שקיעה. לפעמים כל מה שצריך זה לשבת כמה דקות בשקט, בלי סמול-טוק מעיק ובלי אנשים ששואלים 'מה המטרות שלך לחמש השנים הקרובות'. שום מטרות, תודה.",
      descEn: "Oversized sweater, cold brew, and twilight air. Sometimes all you need is five quiet minutes without awkward small talk or anyone asking about your 'five-year plan'. Zero plans, thank you."
    },
    {
      id: "protein",
      artImage: "images/art/protein.jpg",
      realImage: "images/post_11_DRwvLwlE1zb.jpg",
      realLabelHe: "הרנט על החלבון 🏋️",
      realLabelEn: "The Whey Rant 🏋️",
      tagHe: "החיים עם ג'ימברו",
      tagEn: "Gym-Bro Partner Life",
      titleHe: "חלבון: החיים בצל אבקות ושייקרים מסוכנים",
      titleEn: "Protein: Life in the Shadow of Whey Isolate",
      descHe: "מאז שהבן זוג נכנס חזק לכושר, כל שיחה בבית נמדדת בגרמים של חלבון איזולט. יש שייקרים עם ריח של נשק ביולוגי בכיור, ואני רק יושבת שם ותוהה איך משיחה רגילה הגענו לחישוב מאקרוז ב-2 בלילה.",
      descEn: "Ever since my partner got into fitness, every conversation is counted in grams of isolate whey. There are forgotten shakers in the sink constituting biohazards, and I'm just sitting there wondering how we got here as a society."
    },
    {
      id: "pencil",
      artImage: "images/art/pencil.jpg",
      realImage: "images/post_12_DRchG3kgm_I.jpg",
      realLabelHe: "הטראומה המקורית ✏️",
      realLabelEn: "Original Trauma Reel ✏️",
      tagHe: "סיפור המקור",
      tagEn: "Origin Story",
      titleHe: "טראומת העט-עיפרון (0.7 מ״מ) מכיתה ד'",
      titleEn: "The 0.7mm Mechanical Pencil Incident",
      descHe: "תמיד שואלים מאיפה הציניות והמבט הקפוא. הכל התחיל בכיתה ד', כשילד אחד הפך את כיס המכנסיים שלי ללוח מטרה לשפיצים 0.7. לא סלחתי לו עד היום, אבל לפחות זה מימן לי אישיות שלמה והומור שחור שעובד מעולה.",
      descEn: "People ask where the deadpan cynicism comes from. In 4th grade a boy perpetually jabbed 0.7mm mechanical pencil lead into my jeans. The trauma remains, but at least it funded a whole personality and great dark humor."
    }
  ],

  posts: [
    {
      id: "DD7n-KhIptn",
      code: "DD7n-KhIptn",
      titleHe: "יא חתיך אחד 🤌",
      titleEn: "Ya Hatich Echad 🤌",
      quoteHe: "יא חתיך אחד 🤌🤌 קח שני צעדים אחורה",
      quoteEn: "You handsome devil 🤌🤌 please take two steps back",
      captionHe: "מחוות ידיים איטלקיות ופלירטוטים אגרסיביים מדי",
      captionEn: "Aggressive Italian hand gestures and questionable flirting techniques",
      category: "dating",
      categoryLabelHe: "דייטים וגברים",
      categoryLabelEn: "Dating & Men",
      image: "images/post_1_DD7n-KhIptn.jpg",
      views: "182K",
      likes: "19.4K",
      date: "2024-12-23",
      url: "https://www.instagram.com/p/DD7n-KhIptn/",
      tagHe: "פלירטוט אגרסיבי",
      tagEn: "Aggressive Flirt"
    },
    {
      id: "DDkS_eUIv9t",
      code: "DDkS_eUIv9t",
      titleHe: "למה אני לסבית",
      titleEn: "Why I'm a Lesbian",
      quoteHe: "הוא חושב על המחמאה הזאת עד היום...",
      quoteEn: "He is still thinking about that compliment to this day...",
      captionHe: "הוא חושב על המחמאה הזאת עד היום וזאת הסיבה המדויקת למה אני לסבית",
      captionEn: "He still thinks about that compliment to this day and that's precisely why I'm a lesbian",
      category: "dating",
      categoryLabelHe: "דייטים וגברים",
      categoryLabelEn: "Dating & Men",
      image: "images/post_2_DDkS_eUIv9t.jpg",
      views: "245K",
      likes: "28.1K",
      date: "2024-12-14",
      url: "https://www.instagram.com/p/DDkS_eUIv9t/",
      tagHe: "קלאסיקה",
      tagEn: "Classic"
    },
    {
      id: "Dc1QeIQCach",
      code: "Dc1QeIQCach",
      titleHe: "בתכלס...",
      titleEn: "Basically...",
      quoteHe: "בתכלס יש לי עוד המון להגיד בנושא, אבל נהיה ארוך וממילא אין קשב.",
      quoteEn: "Truth is I have so much more to say, but it got long and nobody has an attention span.",
      captionHe: "יש לי עוד להגיד בנושא אבל נהיה ארוך",
      captionEn: "I have more to say on the matter but it got way too long",
      category: "rant",
      categoryLabelHe: "רנטים ודעות",
      categoryLabelEn: "Unfiltered Rants",
      image: "images/post_3_Dc1QeIQCach.jpg",
      views: "138K",
      likes: "14.2K",
      date: "2026-09-03",
      url: "https://www.instagram.com/p/Dc1QeIQCach/",
      tagHe: "טייק רותח",
      tagEn: "Hot Take"
    },
    {
      id: "DcwHOeJiqKg",
      code: "DcwHOeJiqKg",
      titleHe: "מנסה להשחיט דירה",
      titleEn: "Apartment Renovation Chaos",
      quoteHe: "מנסה להשחיט דירה. זרקו רעיונות בבקשה לפני שהמשכיר מגלה.",
      quoteEn: "Trying to renovate/destroy my apartment. Send ideas before the landlord notices.",
      captionHe: "זרקו רעיונות בבקשה וכל מי שחזר ללימודים אז שיבושם לו יום ראשון שמח",
      captionEn: "Drop ideas please, and whoever went back to school good for you happy Sunday",
      category: "lifestyle",
      categoryLabelHe: "כאוס יומיומי",
      categoryLabelEn: "Daily Chaos",
      image: "images/post_4_DcwHOeJiqKg.jpg",
      views: "164K",
      likes: "17.9K",
      date: "2026-09-01",
      url: "https://www.instagram.com/p/DcwHOeJiqKg/",
      tagHe: "שיפוצים וכאוס",
      tagEn: "DIY Panic"
    },
    {
      id: "DSQBX0kgnMB",
      code: "DSQBX0kgnMB",
      titleHe: "מקווה שעזרתי לכן",
      titleEn: "Hope I Helped You Girls",
      quoteHe: "מקווה שעזרתי לכן, ואם לא - לפחות שרפתי לכן 40 שניות מהחיים.",
      quoteEn: "Hope I helped you girls. If not, at least I burned 40 seconds off your day.",
      captionHe: "מקווה שעזרתי לכן",
      captionEn: "Tips I learned the hard way so you don't have to suffer through it",
      category: "lifestyle",
      categoryLabelHe: "עצות לחיים",
      categoryLabelEn: "Life Tips",
      image: "images/post_5_DSQBX0kgnMB.jpg",
      views: "310K",
      likes: "34.5K",
      date: "2025-12-14",
      url: "https://www.instagram.com/p/DSQBX0kgnMB/",
      tagHe: "עצה כנה",
      tagEn: "Honest Advice"
    },
    {
      id: "DR2KOUtAh0b",
      code: "DR2KOUtAh0b",
      titleHe: "לא תביאו לי באינגייג'מנט?",
      titleEn: "Won't You Give Engagement?",
      quoteHe: "אין משהו יותר מביך מלהתחנן לאינגייג'מנט, אבל הנה אני עושה את זה.",
      quoteEn: "Nothing is more humiliating than begging for engagement, yet here I am.",
      captionHe: "לא תביאו לי באינגייג'מנט תעשו טובה",
      captionEn: "Drop some engagement do me a favor",
      category: "rant",
      categoryLabelHe: "רנטים ודעות",
      categoryLabelEn: "Unfiltered Rants",
      image: "images/post_6_DR2KOUtAh0b.jpg",
      views: "225K",
      likes: "25.1K",
      date: "2025-12-12",
      url: "https://www.instagram.com/p/DR2KOUtAh0b/",
      tagHe: "אינגייג'מנט",
      tagEn: "Engagement"
    },
    {
      id: "DRzRYB3At6n",
      code: "DRzRYB3At6n",
      titleHe: "חיכה שנתיים שלמות",
      titleEn: "Waited Two Whole Years",
      quoteHe: "הוא חיכה שנתיים שלמות לשלוף את זה. אנשים שומרים טינה טוב יותר מבנקים.",
      quoteEn: "He waited two full years to bring it up. People hoard petty grudges like treasure.",
      captionHe: "חיכה שנתיים שלמות לשלוף את זה",
      captionEn: "Waited two whole years to pull that out",
      category: "dating",
      categoryLabelHe: "דייטים וגברים",
      categoryLabelEn: "Dating & Men",
      image: "images/post_7_DRzRYB3At6n.jpg",
      views: "198K",
      likes: "22.3K",
      date: "2025-12-11",
      url: "https://www.instagram.com/p/DRzRYB3At6n/",
      tagHe: "טינה של גברים",
      tagEn: "Petty Men"
    },
    {
      id: "DRzE3nygvmH",
      code: "DRzE3nygvmH",
      titleHe: "לאן הגענו כחברה",
      titleEn: "Where Did Society Go",
      quoteHe: "לאן לעזאזל הגענו כחברה? אני תוהה את זה כל פעם שאני פותחת טיקטוק.",
      quoteEn: "Where the hell did we go as a society? I wonder every time I open TikTok.",
      captionHe: "לאן הגענו כחברה שזאת השיחה שלנו",
      captionEn: "Where did we go as a society that this is the conversation",
      category: "rant",
      categoryLabelHe: "רנטים ודעות",
      categoryLabelEn: "Unfiltered Rants",
      image: "images/post_8_DRzE3nygvmH.jpg",
      views: "280K",
      likes: "31.2K",
      date: "2025-12-11",
      url: "https://www.instagram.com/p/DRzE3nygvmH/",
      tagHe: "משבר חברתי",
      tagEn: "Social Crisis"
    },
    {
      id: "DRxU2idgsJU",
      code: "DRxU2idgsJU",
      titleHe: "קפוצ'ון ענק וחרדות",
      titleEn: "Oversized Hoodie & Dread",
      quoteHe: "שחררי את הלסת. תורידי את הכתפיים. קחי שלוק מים. הכל בסדר.",
      quoteEn: "Unclench your jaw. Drop your shoulders down. Sip some water. You're fine.",
      captionHe: "איך שרדנו עד עכשיו ומה התוכנית",
      captionEn: "How we survived until now and what's the plan",
      category: "dark",
      categoryLabelHe: "הומור שחור",
      categoryLabelEn: "Dark Humor",
      image: "images/post_9_DRxU2idgsJU.jpg",
      views: "340K",
      likes: "42.1K",
      date: "2025-12-10",
      url: "https://www.instagram.com/p/DRxU2idgsJU/",
      tagHe: "שחררי את הלסת",
      tagEn: "Jaw Check"
    },
    {
      id: "DRxB_56AqXB",
      code: "DRxB_56AqXB",
      titleHe: "תיאוריית הזומבים",
      titleEn: "The Zombie Bite Theory",
      quoteHe: "כשהייתי קטנה חשבתי שחסרי דיור הם זומבים שיכולים להדביק בנשיכה. מסתבר שכולנו קצת זומבים.",
      quoteEn: "As a kid I thought homeless people were zombies who bite you. Turns out adulthood made us all zombies.",
      captionHe: "חשבתי שהם זומבים שיכולים להדביק אותך בנשיכה",
      captionEn: "Thought they were zombies that could infect you with a bite",
      category: "dark",
      categoryLabelHe: "הומור שחור",
      categoryLabelEn: "Dark Humor",
      image: "images/post_10_DRxB_56AqXB.jpg",
      views: "512K",
      likes: "61.8K",
      date: "2025-12-10",
      url: "https://www.instagram.com/p/DRxB_56AqXB/",
      tagHe: "טראומת ילדות",
      tagEn: "Core Memory"
    },
    {
      id: "DRwvLwlE1zb",
      code: "DRwvLwlE1zb",
      titleHe: "התחרות הסמויה",
      titleEn: "The Covert Competition",
      quoteHe: "מכירים את התחרות הסמויה הזאת? ...לפחות אין לו אפילפסיה יותר (כי הוא לא כאן).",
      quoteEn: "You know that petty rivalry? ...At least he doesn't have epilepsy anymore (he's gone).",
      captionHe: "לפחות אין לו אפילפסיה יותר (כי הוא לא כאן)",
      captionEn: "At least he doesn't have epilepsy anymore (because he's not here)",
      category: "dark",
      categoryLabelHe: "הומור שחור",
      categoryLabelEn: "Dark Humor",
      image: "images/post_11_DRwvLwlE1zb.jpg",
      views: "590K",
      likes: "78.4K",
      date: "2025-12-02",
      url: "https://www.instagram.com/p/DRwvLwlE1zb/",
      tagHe: "שיא ההומור השחור",
      tagEn: "Peak Dark Humor"
    },
    {
      id: "DRchG3kgm_I",
      code: "DRchG3kgm_I",
      titleHe: "טראומת העט-עיפרון ביסודי",
      titleEn: "Mechanical Pencil Trauma",
      quoteHe: "היה ילד שתמיד היה תוקע את החוד של העט עפרון שלו בישבן שלי. ועדיין שואלים למה אני כזאת.",
      quoteEn: "A kid perpetually jabbed 0.7mm pencil lead into my butt. And you wonder why I'm like this.",
      captionHe: "כשהייתי ביסודי היה ילד שתמיד היה תוקע את החוד של העט עפרון שלו בישבן שלי",
      captionEn: "In elementary school a boy always poked pencil lead into my butt",
      category: "dark",
      categoryLabelHe: "הומור שחור",
      categoryLabelEn: "Dark Humor",
      image: "images/post_12_DRchG3kgm_I.jpg",
      views: "430K",
      likes: "53.7K",
      date: "2025-11-24",
      url: "https://www.instagram.com/p/DRchG3kgm_I/",
      tagHe: "סיפור מקור",
      tagEn: "Origin Story"
    }
  ],

  cynicQuotes: [
    {
      he: "הוא חושב על המחמאה הזאת עד היום... וזאת בדיוק הסיבה למה עדיף שקט.",
      en: "He's still thinking about that compliment to this day... which is precisely why silence is superior."
    },
    {
      he: "לפחות אין לו אפילפסיה יותר (כי הוא לא כאן). שחור? קצת. נכון? מאוד.",
      en: "At least he doesn't have epilepsy anymore (because he's gone). Dark? Yes. True? Very."
    },
    {
      he: "לאן לעזאזל הגענו כחברה? אני תוהה את זה כל פעם שאני פותחת טיקטוק.",
      en: "Where the hell did we go as a society? I wonder every time I open TikTok."
    },
    {
      he: "כשהייתי קטנה חשבתי שחסרי דיור הם זומבים שיכולים להדביק בנשיכה. היום אני מבינה שכולנו קצת זומבים.",
      en: "As a kid I thought homeless people were zombies who bite. Now I realize adulthood bit all of us."
    },
    {
      he: "חלבון. מאז שהבן זוג נכנס לכושר, כל הבית מריח כמו וניל מלאכותי של שייקר ודיכאון קל.",
      en: "Protein. Ever since my partner got fit, the entire apartment smells like artificial vanilla and mild dread."
    },
    {
      he: "אין משהו יותר מביך מלהתחנן לאינגייג'מנט, אבל הנה אני עושה את זה בכל זאת. תעשו לייק לפני שאתחרט.",
      en: "Nothing is more embarrassing than begging for engagement, yet here I am. Drop a like before I regret it."
    },
    {
      he: "היה ילד ביסודי שתקע לי עט-עיפרון בישבן. זאת הייתה ההכנה הכי טובה לעולם המבוגרים.",
      en: "A kid jabbed mechanical pencil lead into my butt in 4th grade. Honestly the best preparation for adulthood."
    },
    {
      he: "יא חתיך אחד 🤌🤌 קח שני צעדים אחורה בבקשה לפני שאני שולפת את חוסר הזמינות הרגשית שלי.",
      en: "You handsome devil 🤌🤌 please take two steps back before I unleash my emotional unavailability."
    },
    {
      he: "מקווה שעזרתי לכן, ואם לא – לפחות בזבזתי לכן עוד 40 שניות מהחיים.",
      en: "Hope I helped you girls. If not, at least I burned 40 seconds off your day."
    },
    {
      he: "חיכה שנתיים שלמות לשלוף את זה. אנשים שומרים טינה קטנונית טוב יותר משבנקים שומרים כסף.",
      en: "He waited two full years to bring it up. People hoard petty grudges better than banks hoard cash."
    },
    {
      he: "בדיקת מערכות: שחררי את הלסת. תורידי כתפיים. קחי שלוק מים. אנחנו סתם על כדור בחלל וזה לא משנה.",
      en: "System check: Unclench your jaw. Drop your shoulders down. Sip some water. We're on a rock in space and you're fine."
    },
    {
      he: "לבטל תוכניות ברגע האחרון כדי להישאר במיטה עם קפה קר זו לא עצלנות, זו שמירה אקטיבית על שפיות.",
      en: "Canceling plans last minute to stay in bed with iced coffee isn't laziness, it's radical sanity."
    }
  ],

  pollOptions: [
    {
      id: "rotting",
      titleHe: "מועדון ה-Bed Rotting (לשכב במיטה בלי רגשות אשם)",
      titleEn: "Bed-Rotting Club (Lying in bed with zero guilt)",
      descHe: "פינה שקטה לפרוק חרדות, לדבר על למה אין כוח לאנשים, ולדעת שכולנו באותה סירה.",
      descEn: "A quiet space to unpack social exhaustion, existential dread, and realize we're all in the same boat.",
      votes: 2140
    },
    {
      id: "podcast",
      titleHe: "פודקאסט קצר: ליה יושבת ומדברת בלי עריכות",
      titleEn: "Raw Mini-Podcast: Liya talking unfiltered",
      descHe: "ליה מול מיקרופון בחדר, מדברת בגובה העיניים על בריאות הנפש, גברים, והחיים בלי שום גינונים.",
      descEn: "Liya sits with a mic in her room, chatting raw about mental health, dating, and modern life.",
      votes: 2490
    },
    {
      id: "advice",
      titleHe: "פינת ייעוץ אדישה: שולחים דילמה ומקבלים רוסט",
      titleEn: "Unbothered Advice Hotline",
      descHe: "שולחים מה מציק לכם בחיים ומקבלים מליה תשובה כנה, צינית ומנחמת שתאפס אתכם.",
      descEn: "Submit your life crisis and get an unfiltered, sarcastic yet comforting reality-check.",
      votes: 1850
    },
    {
      id: "hoodie",
      titleHe: "קפוצ'ונים אוברסייז של 'לאן הגענו כחברה'",
      titleEn: "'Where Did Society Go Wrong' Oversized Hoodies",
      descHe: "קפוצ'ון עבה ורחב להתחבא בו כל החורף במיטה בלי לראות אף אחד.",
      descEn: "Heavyweight hoodies to hide in all winter without seeing anyone.",
      votes: 1420
    }
  ],

  confessions: [
    {
      author: "מישהי שלא יצאה מהמיטה מהבוקר",
      authorEn: "Bed-rotter since 8 AM",
      textHe: "ביטלתי עכשיו תוכניות בתירוץ שאני 'לא מרגישה טוב' כשבפועל אני פשוט עם קפה קר וסרטונים של ליה בטיקטוק. השפיות שלי מודה לך.",
      textEn: "Just flaked on plans saying I'm 'under the weather' when I'm literally in bed with iced coffee watching Liya's reels. My sanity thanks you.",
      timestamp: "לפני שעתיים",
      timestampEn: "2h ago"
    },
    {
      author: "שורד שפיצים 0.7 מ״מ",
      authorEn: "0.7mm Lead Survivor",
      textHe: "כשסיפרת על הילד מהיסודי עם העט-עיפרון בכיתי מצחוק. עד היום הצליל של קליק בעט מעלה לי את הדופק.",
      textEn: "When you told that mechanical pencil story I cried laughing. To this day a pen click spikes my pulse.",
      timestamp: "לפני יום",
      timestampEn: "1d ago"
    },
    {
      author: "אנונימית עם שייקר מסריח",
      authorEn: "Partner of a Gym Bro",
      textHe: "הבן זוג שלי מכין שייק חלבון ב-6 בבוקר והבלנדר עושה רעש של מסור חשמלי. מבינה עכשיו כל מילה שאמרת על הג'ימברוז.",
      textEn: "My partner blends whey protein at 6 AM sounding like a chainsaw. I now feel every single word you said.",
      timestamp: "אתמול",
      timestampEn: "Yesterday"
    }
  ],

  translations: {
    he: {
      siteTitle: "ליה • notliya.com | הפינה של ליה",
      navLore: "הסיפורים",
      navGallery: "גלריית איורים",
      navVault: "סרטונים",
      navOracle: "הפאנצ'ומטר",
      navClubhouse: "המועדון",
      statusText: "ערה ב-3 בלילה, גוללת במיטה",
      creatorNoteBadge: "הערה אישית ממי שבנה את האתר ✍️",
      creatorNoteText: "היי ליה, ראיתי ששאלת בסטורי איזה אתר לבנות, וזה נשמע לי כמו פרויקט ממש מעניין אז פשוט ישבתי ובניתי לך אותו. קניתי גם את notliya.com כי חבל שיתפסו אותו. אם בא לך עליו – רק תגידי, אני מעביר לך את כל הגישה והמפתחות באהבה.",
      forLiyaBtn: "ליה, קחי את האתר (הוא שלך) 🔑",
      heroPunchline: "פאנצ'ים שיכלתי לזרוק ואהבה שיכלתי לקבל.",
      heroSub: "בלי אלגוריתמים מעצבנים ובלי פוזה. מקום אינטימי לשבת במיטה, לראות סרטונים, לצחוק על החיים ולפרוק חרדות.",
      btnVault: "לכל הסרטונים 🎬",
      btnOracle: "תני לי פאנץ' 🔮",
      btnGallery: "גלריית האיורים 🎨",
      statTiktok: "בטיקטוק",
      statLikes: "לייקים",
      statIg: "באינסטגרם",
      statPeace: "רעשי רקע",
      themeBarTitle: "🎨 פלטת צבעים:",
      galleryTitle: "גלריית האיורים והעולם של ליה",
      gallerySubtitle: "כל האילוסטרציות המקוריות שנוצרו במיוחד עבור ליה בסגנונות שונים.",
      storiesTitle: "הלור של ליה: מאיפה הכל התחיל?",
      storiesSubtitle: "האיורים המקוריים לצד הפריימים מהסרטונים האמיתיים. שקט נפשי, חלבון וטראומות ילדות.",
      vaultTitle: "סרטונים ששווה לראות שוב ושוב",
      vaultSubtitle: "כל הרנטים, ההתמוטטויות והפאנצ'ים שנשמרו.",
      filterAll: "הכל (12)",
      filterDark: "הומור שחור",
      filterDating: "דייטים וגברים",
      filterRant: "רנטים ודעות",
      filterLifestyle: "חיים וכאוס",
      oracleTitle: "הפאנצ'ומטר: עצות לשעות הקטנות של הלילה",
      oracleSubtitle: "תקועה עם דילמה? חרדה לא מוסברת במיטה? קבלי תשובה כנה ואדישה מליה.",
      oraclePlaceholder: "כתבי מה עובר עלייך (למשל: הוא ראה את הסטורי ולא ענה להודעה...)",
      oracleBtn: "תני כאפה של מציאות 💥",
      oracleSanityBtn: "שחררי את הלסת 🛟",
      oracleCopied: "הועתק ללוח!",
      oracleCopyBtn: "📋 העתק ציטוט",
      copySiteLink: "העתיקי את notliya.com לסטורי 📋",
      clubhouseTitle: "איזה פיצ'ר שווה שיהיה באתר?",
      clubhouseSubtitle: "במקום לנחש מה לפתח – הצביעו לרעיון המועדף עליכם או זרקו רעיון חדש.",
      voteBtn: "הצביעו",
      votedText: "הצבעתם ✓",
      pitchPlaceholder: "יש לך רעיון מגניב אחר לאתר? כתבי כאן...",
      pitchSubmitBtn: "שלחי הצעה",
      confessTitle: "פתקים אנונימיים לתוך הריק",
      confessSubtitle: "דברים מביכים שאף אחד לא יגיד בקול.",
      confessPlaceholder: "שתפי סיפור מביך או תלונה על החיים בלי שמות...",
      confessAuthorPlaceholder: "כינוי (או השאירי ריק לאנונימי)",
      confessSubmitBtn: "שגרי לריק 💀",
      footerCredits: "נבנה באופן אישי עבור @not.liya כפרויקט עצמאי לכיף. רוצה את האתר? שלחי הודעה.",
      soundOn: "סאונד פעיל",
      soundOff: "השתק",
      openInIg: "צפי בסרטון המקורי באינסטגרם ↗",
      modalClose: "סגור (Esc)"
    },
    en: {
      siteTitle: "Liya • notliya.com | The Chill Corner",
      navLore: "Stories",
      navGallery: "Artworks",
      navVault: "Videos",
      navOracle: "The Oracle",
      navClubhouse: "The Club",
      statusText: "Awake at 3 AM, bed-rotting",
      creatorNoteBadge: "Personal note from the creator ✍️",
      creatorNoteText: "Hey Liya, I saw your story asking what site to build, and it sounded like such an interesting project so I sat down and made one for you. I also bought notliya.com so nobody else grabs it. If you want it, just let me know and I'll hand over full keys and ownership.",
      forLiyaBtn: "Hey Liya, take the keys (it's yours) 🔑",
      heroPunchline: "Punchlines I could have thrown and love I could have received.",
      heroSub: "No fake algorithms, no PR facade. An intimate space to sit in bed, watch reels, laugh at life, and unpack anxiety.",
      btnVault: "Watch Videos 🎬",
      btnOracle: "Ask The Oracle 🔮",
      btnGallery: "Art Gallery 🎨",
      statTiktok: "on TikTok",
      statLikes: "Likes",
      statIg: "on Instagram",
      statPeace: "Background Noise",
      themeBarTitle: "🎨 Color Palette:",
      galleryTitle: "Original Artwork Gallery & Visual Lore",
      gallerySubtitle: "Bespoke illustrations crafted exclusively for Liya across different creative styles.",
      storiesTitle: "The Lore: How Did We Get Here?",
      storiesSubtitle: "Original artwork paired with real video frames. Bed-rotting, whey protein, and childhood trauma.",
      vaultTitle: "Reels Worth Re-watching at 2 AM",
      vaultSubtitle: "Every viral hit, existential rant, and deadpan social observation.",
      filterAll: "All (12)",
      filterDark: "Dark Humor",
      filterDating: "Dating & Men",
      filterRant: "Rants & Takes",
      filterLifestyle: "Daily Chaos",
      oracleTitle: "The Cynic Oracle: Late-Night Reality Checks",
      oracleSubtitle: "Got a dilemma? Unexplained existential dread in bed? Get an unbothered, honest answer.",
      oraclePlaceholder: "Type your dilemma (e.g., He saw my story but left my text on read...)",
      oracleBtn: "Roast My Dilemma 💥",
      oracleSanityBtn: "Unclench Your Jaw 🛟",
      oracleCopied: "Copied to clipboard!",
      oracleCopyBtn: "📋 Copy quote",
      copySiteLink: "Copy notliya.com for Stories 📋",
      clubhouseTitle: "What feature should Liya keep on the site?",
      clubhouseSubtitle: "Instead of guessing what to build — vote for your favorite idea or pitch a new one.",
      voteBtn: "Vote",
      votedText: "Voted ✓",
      pitchPlaceholder: "Got another fun concept for the site? Pitch it here...",
      pitchSubmitBtn: "Send Idea",
      confessTitle: "Anonymous Notes into the Void",
      confessSubtitle: "Embarrassing things nobody will ever admit out loud.",
      confessPlaceholder: "Share an awkward story or grievance anonymously...",
      confessAuthorPlaceholder: "Nickname (or leave blank for Anon)",
      confessSubmitBtn: "Drop into the Void 💀",
      footerCredits: "Built personally for @not.liya as an independent project for fun. Want the site? Just hit me up.",
      soundOn: "Sound On",
      soundOff: "Muted",
      openInIg: "Watch Original Reel on Instagram ↗",
      modalClose: "Close (Esc)"
    }
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = SITE_DATA;
}
