const SITE_DATA = {
  profile: {
    name: "ליה",
    englishName: "Liya",
    handle: "@not.liya",
    instagramUrl: "https://www.instagram.com/not.liya/",
    tiktokUrl: "https://www.tiktok.com/@not.liya",
    artPortrait: "images/art/portrait.jpg",
    artCoffee: "images/art/coffee.jpg",
    artProtein: "images/art/protein.jpg",
    artPencil: "images/art/pencil.jpg",
    avatar: "images/avatar.jpg",
    bioHe: "פאנצ'ים שיכלתי לזרוק, אהבה שיכלתי לקבל, ופרישה מוקדמת מרעשי רקע.",
    bioEn: "Punchlines I could have thrown, love I could have received, and an early retirement from the noise.",
    manifestoHe: "פעם רדפתי אחרי מיליוני צפיות בעולם. היום אני פה, מדברת בגובה העיניים, בלי בולשיט ובלי פילטרים. פינה אינטימית לפרוק חרדות, לצחוק על החיים, ולתהות לאן לעזאזל הגענו כחברה.",
    manifestoEn: "Once chased millions of vanity metrics globally. Today I'm here, keeping it completely unfiltered with the real ones. An intimate clubhouse to unpack anxiety, laugh at life, and wonder where society went wrong."
  },

  stories: [
    {
      id: "coffee",
      image: "images/art/coffee.jpg",
      tagHe: "שקט נפשי והדחקה",
      tagEn: "Peace of Mind & Repression",
      titleHe: "אייס קפה, מיטה, וחוסר עניין מוחלט בסמול-טוק",
      titleEn: "Iced Coffee, Bed-Rotting, and Zero Social Battery",
      descHe: "למחוק את הרעש העולמי היה הצעד הכי בריא שעשיתי. לפעמים להישאר מתחת לשמיכה עם אייס קפה ולבהות בתקרה זו לא עצלנות, זו שמירה אקטיבית על שפיות. אם תתעלמי מבעיות מספיק זמן הן כנראה לא ייעלמו, אבל לפחות יש מזגן.",
      descEn: "Tuning out the international noise was the best mental health decision I ever made. Sometimes staying in bed with iced coffee isn't laziness, it's radical sanity preservation. If you ignore your problems they won't vanish, but at least there's air conditioning."
    },
    {
      id: "protein",
      image: "images/art/protein.jpg",
      tagHe: "רוסט על ג'ימברוז",
      tagEn: "Gym Bro Chronicles",
      titleHe: "חלבון: מאז שהבן זוג שלי נכנס לכושר",
      titleEn: "Protein: Life in the Shadow of Whey Isolate",
      descHe: "הבית שלנו הפך למחסן אבקות תעשייתי. כל כוס מים נמדדת, כל נשימה מחושבת בגרמים של חלבון איזולט, ושייקרים שלא נשטפו בזמן מאיימים על שלום הציבור. הוא חושב על המשקלים, אני חושבת על לאן לעזאזל הגענו כחברה.",
      descEn: "Our apartment turned into an industrial whey distribution center. Every conversation is measured in grams of protein, lukewarm water, and forgotten shakers creating biohazards. He counts macros, I contemplate where society went wrong."
    },
    {
      id: "pencil",
      image: "images/art/pencil.jpg",
      tagHe: "סיפור המקור",
      tagEn: "Origin Story",
      titleHe: "טראומת העט-עיפרון (0.7 מ״מ) ביסודי",
      titleEn: "The 0.7mm Mechanical Pencil Incident",
      descHe: "אנשים שואלים מאיפה הציניות והמבט הקפוא? בכיתה ד' היה ילד שהפך את כיס המכנסיים שלי למטרה סדרתית של שפיצים גרפיט. הטראומה עדיין שם, אבל לפחות היא מימנה אישיות שלמה והומור שחור שעובד מעולה.",
      descEn: "People wonder why I'm cynical and deadpan. In 4th grade a boy perpetually jabbed 0.7mm mechanical pencil lead into my butt. The trauma remains, but at least it forged a complete personality and elite dark humor."
    }
  ],

  posts: [
    {
      id: "DD7n-KhIptn",
      code: "DD7n-KhIptn",
      titleHe: "יא חתיך אחד",
      titleEn: "Ya Hatich Echad",
      quoteHe: "יא חתיך אחד 🤌🤌",
      quoteEn: "You handsome devil 🤌🤌",
      captionHe: "מחוות ידיים איטלקיות ופלירטוטים אגרסיביים מדי",
      captionEn: "Aggressive Italian hand gestures and questionable flirting techniques",
      category: "dating",
      categoryLabelHe: "דייטים וגברים",
      categoryLabelEn: "Dating & Men",
      image: "images/post_1_DD7n-KhIptn.jpg",
      views: "182K",
      likes: "19.4K",
      date: "2024-12-23",
      url: "https://www.instagram.com/p/DD7n-KhIptn/",
      tagHe: "פלירטוט ויראלי",
      tagEn: "Viral Flirt"
    },
    {
      id: "DDkS_eUIv9t",
      code: "DDkS_eUIv9t",
      titleHe: "למה אני לסבית",
      titleEn: "Why I'm a Lesbian",
      quoteHe: "הוא חושב על המחמאה הזאת עד היום...",
      quoteEn: "He is still thinking about that compliment to this day...",
      captionHe: "הוא חושב על המחמאה הזאת עד היום וזאת הסיבה המדויקת למה אני לסבית",
      captionEn: "He still thinks about that compliment to this day and that's precisely why I'm a lesbian",
      category: "dating",
      categoryLabelHe: "דייטים וגברים",
      categoryLabelEn: "Dating & Men",
      image: "images/post_2_DDkS_eUIv9t.jpg",
      views: "245K",
      likes: "28.1K",
      date: "2024-12-14",
      url: "https://www.instagram.com/p/DDkS_eUIv9t/",
      tagHe: "אהוב הקהל",
      tagEn: "Fan Favorite"
    },
    {
      id: "Dc1QeIQCach",
      code: "Dc1QeIQCach",
      titleHe: "בתכלס...",
      titleEn: "Basically...",
      quoteHe: "בתכלס יש לי עוד המון להגיד בנושא, אבל נהיה ארוך וממילא אין קשב.",
      quoteEn: "Truth is I have so much more to say, but it got long and nobody has an attention span.",
      captionHe: "יש לי עוד להגיד בנושא אבל נהיה ארוך",
      captionEn: "I have more to say on the matter but it got way too long",
      category: "rant",
      categoryLabelHe: "רנטים ודעות",
      categoryLabelEn: "Unfiltered Rants",
      image: "images/post_3_Dc1QeIQCach.jpg",
      views: "138K",
      likes: "14.2K",
      date: "2026-09-03",
      url: "https://www.instagram.com/p/Dc1QeIQCach/",
      tagHe: "טייק רותח",
      tagEn: "Hot Take"
    },
    {
      id: "DcwHOeJiqKg",
      code: "DcwHOeJiqKg",
      titleHe: "מנסה להשחיט דירה",
      titleEn: "Apartment Demolition Phase",
      quoteHe: "מנסה להשחיט דירה. זרקו רעיונות בבקשה לפני שהמשכיר מגלה.",
      quoteEn: "Trying to renovate/destroy my apartment. Send ideas before the landlord notices.",
      captionHe: "זרקו רעיונות בבקשה וכל מי שחזר ללימודים אז שיבושם לו יום ראשון שמח",
      captionEn: "Drop ideas please, and whoever went back to school good for you happy Sunday",
      category: "lifestyle",
      categoryLabelHe: "כאוס יומיומי",
      categoryLabelEn: "Daily Chaos",
      image: "images/post_4_DcwHOeJiqKg.jpg",
      views: "164K",
      likes: "17.9K",
      date: "2026-09-01",
      url: "https://www.instagram.com/p/DcwHOeJiqKg/",
      tagHe: "שיפוצים וכאוס",
      tagEn: "DIY Panic"
    },
    {
      id: "DSQBX0kgnMB",
      code: "DSQBX0kgnMB",
      titleHe: "מקווה שעזרתי לכן",
      titleEn: "Hope I Helped You Girls",
      quoteHe: "מקווה שעזרתי לכן, ואם לא - לפחות שרפתי לכן 40 שניות מהחיים.",
      quoteEn: "Hope I helped you girls. If not, at least I wasted 40 seconds of your life.",
      captionHe: "מקווה שעזרתי לכן",
      captionEn: "Tips I learned the hard way so you don't have to suffer through it",
      category: "advice",
      categoryLabelHe: "עצות מפוקפקות",
      categoryLabelEn: "Dubious Advice",
      image: "images/post_5_DSQBX0kgnMB.jpg",
      views: "310K",
      likes: "34.5K",
      date: "2025-12-14",
      url: "https://www.instagram.com/p/DSQBX0kgnMB/",
      tagHe: "עצה לחיים",
      tagEn: "Life Advice"
    },
    {
      id: "DR2KOUtAh0b",
      code: "DR2KOUtAh0b",
      titleHe: "חלבון (מאז שהבן זוג שלי...)",
      titleEn: "Protein (Boyfriend Gym Era)",
      quoteHe: "מאז שהבן זוג שלי נכנס לכושר, כל החיים שלי זה אבקות וחלבון.",
      quoteEn: "Since my boyfriend entered his gym era, our home is an industrial whey protein facility.",
      captionHe: "חלבון. זה כל האישיות של אנשים עכשיו",
      captionEn: "Protein. That is literally everyone's entire personality now",
      category: "dating",
      categoryLabelHe: "דייטים וגברים",
      categoryLabelEn: "Dating & Men",
      image: "images/post_6_DR2KOUtAh0b.jpg",
      views: "420K",
      likes: "51.2K",
      date: "2025-12-04",
      url: "https://www.instagram.com/p/DR2KOUtAh0b/",
      tagHe: "רוסט על ג'ימברוז",
      tagEn: "Gym Bro Roast"
    },
    {
      id: "DRzRYB3At6n",
      code: "DRzRYB3At6n",
      titleHe: "אין משהו יותר מביך",
      titleEn: "Nothing More Humiliating",
      quoteHe: "אין משהו יותר מביך מלהתחנן לאינגייג'מנט, אבל הנה אני פה. לא תביאו לי?",
      quoteEn: "Nothing is more embarrassing than begging for engagement, yet here I stand. Won't you give me some?",
      captionHe: "לא תביאו לי באינגיימנט?",
      captionEn: "Won't you give me some engagement?",
      category: "rant",
      categoryLabelHe: "רנטים ודעות",
      categoryLabelEn: "Unfiltered Rants",
      image: "images/post_7_DRzRYB3At6n.jpg",
      views: "195K",
      likes: "22.8K",
      date: "2025-12-03",
      url: "https://www.instagram.com/p/DRzRYB3At6n/",
      tagHe: "מטא-הומור",
      tagEn: "Meta Humor"
    },
    {
      id: "DRzE3nygvmH",
      code: "DRzE3nygvmH",
      titleHe: "חיכה שנתיים להגיד לי",
      titleEn: "Waited 2 Years to Bring It Up",
      quoteHe: "חיכה שנתיים שלמות לשלוף את זה. הלוואי שהייתה לי כזאת מסירות לפנסיה שלי.",
      quoteEn: "He waited two whole years just to drop that on me. Wish I had that dedication to my 401k.",
      captionHe: "חיכה שנתיים להגיד לי",
      captionEn: "People who hoard resentment at an Olympic medal level",
      category: "dating",
      categoryLabelHe: "דייטים וגברים",
      categoryLabelEn: "Dating & Men",
      image: "images/post_8_DRzE3nygvmH.jpg",
      views: "278K",
      likes: "31.0K",
      date: "2025-12-03",
      url: "https://www.instagram.com/p/DRzE3nygvmH/",
      tagHe: "שמירת טינה",
      tagEn: "Petty Grudges"
    },
    {
      id: "DRxU2idgsJU",
      code: "DRxU2idgsJU",
      titleHe: "לאן לעזאזל הגענו כחברה",
      titleEn: "Where Did We Go as a Society",
      quoteHe: "לאן לעזאזל הגענו כחברה? פחד אמיתי שלי זה הדבר הזה, ולהיכנס להיריון.",
      quoteEn: "Where on earth did we go wrong as a society? My two deepest fears: this, and accidental pregnancy.",
      captionHe: "פחד אמיתי שלי זה ולהיכנס להיריון",
      captionEn: "A genuine fear of mine is that, plus getting pregnant",
      category: "dark",
      categoryLabelHe: "הומור שחור",
      categoryLabelEn: "Dark Humor",
      image: "images/post_9_DRxU2idgsJU.jpg",
      views: "360K",
      likes: "44.9K",
      date: "2025-12-02",
      url: "https://www.instagram.com/p/DRxU2idgsJU/",
      tagHe: "חרדה קיומית",
      tagEn: "Existential Dread"
    },
    {
      id: "DRxB_56AqXB",
      code: "DRxB_56AqXB",
      titleHe: "כשהייתי קטנה: תיאוריית הזומבים",
      titleEn: "Childhood Zombie Theory",
      quoteHe: "כשהייתי קטנה חשבתי שחסרי דיור הם כמו זומבים שיכולים להדביק אותך בנשיכה.",
      quoteEn: "When I was little I was convinced homeless people were zombies that pass poverty via biting.",
      captionHe: "כשהייתי קטנה חשבתי שחסרי דיור הם כמו זומבים שיכולים להדביק אותך בנשיכה",
      captionEn: "When I was little I thought homeless people were like zombies who infect you if they bite you",
      category: "dark",
      categoryLabelHe: "הומור שחור",
      categoryLabelEn: "Dark Humor",
      image: "images/post_10_DRxB_56AqXB.jpg",
      views: "510K",
      likes: "62.3K",
      date: "2025-12-02",
      url: "https://www.instagram.com/p/DRxB_56AqXB/",
      tagHe: "טראומת ילדות",
      tagEn: "Core Memory"
    },
    {
      id: "DRwvLwlE1zb",
      code: "DRwvLwlE1zb",
      titleHe: "התחרות הסמויה",
      titleEn: "The Covert Competition",
      quoteHe: "מכירים את התחרות הסמויה הזאת? ...לפחות אין לו אפילפסיה יותר (כי הוא לא כאן).",
      quoteEn: "You know that secret competition? ...At least he doesn't have epilepsy anymore (because he's not here).",
      captionHe: "לפחות אין לו אפילפסיה יותר (כי הוא לא כאן)",
      captionEn: "At least he doesn't have epilepsy anymore (because he's not here)",
      category: "dark",
      categoryLabelHe: "הומור שחור",
      categoryLabelEn: "Dark Humor",
      image: "images/post_11_DRwvLwlE1zb.jpg",
      views: "590K",
      likes: "78.4K",
      date: "2025-12-02",
      url: "https://www.instagram.com/p/DRwvLwlE1zb/",
      tagHe: "שיא ההומור השחור",
      tagEn: "Peak Dark Humor"
    },
    {
      id: "DRchG3kgm_I",
      code: "DRchG3kgm_I",
      titleHe: "טראומת העט-עיפרון ביסודי",
      titleEn: "Mechanical Pencil Trauma",
      quoteHe: "היה ילד שתמיד היה תוקע את החוד של העט עפרון שלו בישבן שלי. ועדיין שואלים למה אני כזאת.",
      quoteEn: "A kid used to perpetually jab 0.7mm mechanical pencil lead into my butt. And you wonder why I'm cynical.",
      captionHe: "כשהייתי ביסודי היה ילד שתמיד היה תוקע את החוד של העט עפרון שלו בישבן שלי",
      captionEn: "When I was in elementary school there was a kid who always poked the lead of his pencil into my butt",
      category: "dark",
      categoryLabelHe: "הומור שחור",
      categoryLabelEn: "Dark Humor",
      image: "images/post_12_DRchG3kgm_I.jpg",
      views: "430K",
      likes: "53.7K",
      date: "2025-11-24",
      url: "https://www.instagram.com/p/DRchG3kgm_I/",
      tagHe: "סיפור מקור",
      tagEn: "Origin Story"
    }
  ],

  cynicQuotes: [
    {
      he: "הוא חושב על המחמאה הזאת עד היום... וזאת הסיבה המדויקת למה אני מעדיפה שקט.",
      en: "He's still thinking about that compliment to this day... which is precisely why I prefer silence."
    },
    {
      he: "לפחות אין לו אפילפסיה יותר (כי הוא לא כאן). שחור? קצת. נכון? מאוד.",
      en: "At least he doesn't have epilepsy anymore (because he's not here). Dark? Yes. Accurate? Extremely."
    },
    {
      he: "לאן לעזאזל הגענו כחברה? אני שואלת את עצמי את זה בכל פעם שאני פותחת את הפיד.",
      en: "Where the hell did we go as a society? I ask myself this every time I open my feed."
    },
    {
      he: "כשהייתי קטנה חשבתי שחסרי דיור הם זומבים שיכולים להדביק אותך בנשיכה. היום אני מבינה שכולנו קצת זומבים.",
      en: "As a kid I thought homeless people were zombies who infect you with a bite. Now I realize we're all a bit zombie."
    },
    {
      he: "חלבון. מאז שהבן זוג שלי נכנס לכושר, כל חדר בבית מריח כמו וניל מלאכותי ודיכאון.",
      en: "Protein. Ever since my partner got fit, every room smells like artificial vanilla and mild depression."
    },
    {
      he: "אין משהו יותר מביך מלהתחנן לאינגייג'מנט, אבל הנה אני עושה את זה בכל זאת. תעשו לייק לפני שאתחרט.",
      en: "Nothing is more embarrassing than begging for engagement, yet here I am. Drop a like before I regret breathing."
    },
    {
      he: "היה ילד ביסודי שתקע לי עט עיפרון בישבן. זאת הייתה ההכנה הכי טובה לעולם המבוגרים.",
      en: "A kid jabbed mechanical pencil lead into my butt in 4th grade. Honestly the best preparation for adulthood."
    },
    {
      he: "יא חתיך אחד 🤌🤌 קח צעד אחורה לפני שאני שולפת את הציניות שלי.",
      en: "You handsome devil 🤌🤌 Take one step back before I unleash my emotional unavailability."
    },
    {
      he: "מקווה שעזרתי לכן, ואם לא - לפחות בזבזתי לכן עוד 40 שניות מהחיים.",
      en: "Hope I helped you girls. If not, at least I burned 40 seconds off your mortal countdown."
    },
    {
      he: "חיכה שנתיים שלמות לשלוף את זה. אנשים שומרים טינה טוב יותר משבנקים שומרים כסף.",
      en: "He waited two full years to bring it up. People hoard petty grudges better than Swiss banks hoard gold."
    },
    {
      he: "בדיקת מערכות: שחררי את הלסת. תורידי את הכתפיים. קחי שלוק מים. אנחנו על סלע בחלל וזה לא משנה.",
      en: "System check: Unclench your jaw. Drop your shoulders. Sip some water. We're on a space rock and it doesn't matter."
    },
    {
      he: "למחוק מיליוני עוקבים זרים כדי להישאר עם הקהילה המקומית זה כמו להחליף מסיבת טבע בקפה קר ושקט בסלון.",
      en: "Trading millions of global vanity followers for a real local community is the ultimate peace of mind."
    }
  ],

  pollOptions: [
    {
      id: "safe_space",
      titleHe: "מועדון 'מרקיבות ביחד' (Safe Space ציני)",
      titleEn: "'Rotting Together' Club (Cynical Safe Space)",
      descHe: "פינה אינטימית לשיתוף חרדות, רנטים קצרים, ודיונים על למה כולנו צריכות שנ\"צ של 14 שעות.",
      descEn: "An intimate space to share existential panic, quick rants, and why we all need a 14-hour nap.",
      votes: 2140
    },
    {
      id: "podcast_void",
      titleHe: "פודקאסט שבועי: 'צועקים לתוך הריק'",
      titleEn: "Weekly Podcast: 'Screaming into the Void'",
      descHe: "ליה יושבת עם מיקרופון ומדברת בגובה העיניים על בריאות הנפש, גברים, והעולם המודרני בלי פילטרים.",
      descEn: "Liya sits with a mic and talks raw about mental health, dating, and modern chaos with zero PR filter.",
      votes: 2490
    },
    {
      id: "roast_hotline",
      titleHe: "מוקד רוסטים ועצות ציניות לחיים",
      titleEn: "Sarcastic Advice Hotline & Personal Roasts",
      descHe: "שולחים דילמה בחיים ומקבלים מליה רוסט אכזרי אבל מנחם שיסדר לכם את הראש.",
      descEn: "Submit your life crisis and receive an unfiltered reality-check roast from Liya.",
      votes: 1850
    },
    {
      id: "merch_drop",
      titleHe: "מרצ' 'חלבון, חרדות ופאנצ'ים'",
      titleEn: "'Whey, Anxiety & Sarcasm' Merch Drop",
      descHe: "אוברסייז קפוצ'ונים עם 'לאן הגענו כחברה', שייקרים ומדבקות לפריקה עצמית.",
      descEn: "Heavyweight hoodies emblazoned with 'Where Did Society Go Wrong', shakers & sticker packs.",
      votes: 1420
    }
  ],

  confessions: [
    {
      author: "אנונימית עם חרדה חברתית",
      authorEn: "Social Anxiety Anon",
      textHe: "נשארתי במסיבה 15 דקות רק כדי שיראו שבאתי, ואז התחבאתי בשירותים עד שהיה מנומס להזמין מונית הביתה. ליה הרילים שלך שומרים אותי שפויה.",
      textEn: "Stayed at a party for 15 mins just to be seen, then hid in the bathroom until it was polite to Uber home. Liya your reels keep me sane.",
      timestamp: "לפני יומיים",
      timestampEn: "2d ago"
    },
    {
      author: "בוגר טראומת עט-עיפרון",
      authorEn: "0.7mm Survivor",
      textHe: "עד היום כשאני רואה עט עיפרון שפיצים 0.7 הדופק שלי עולה ל-140. ליה את הריפוי שלי.",
      textEn: "To this day when I see a 0.7mm mechanical pencil my heart rate spikes to 140. Liya your videos are therapy.",
      timestamp: "לפני 4 ימים",
      timestampEn: "4d ago"
    },
    {
      author: "חובבת ביטול תוכניות",
      authorEn: "Professional Flaker",
      textHe: "הרגשתי אשמה שביטלתי דייט כדי לבהות בתקרה, עד שראיתי את הסרטון שלך על שקט נפשי. תודה שנתת לגיטימציה לבטלה.",
      textEn: "Felt guilty for canceling a date to stare at the ceiling, until I saw your video on peace of mind. Thanks for legitimizing my bed-rot.",
      timestamp: "אתמול",
      timestampEn: "Yesterday"
    }
  ],

  translations: {
    he: {
      siteTitle: "ליה • notliya.com | הפינה האינטימית שלנו",
      navLore: "הסיפור",
      navVault: "הסרטונים",
      navOracle: "הפאנצ'ומטר",
      navClubhouse: "המועדון",
      statusText: "מחוברת ושופטת באהבה",
      forLiyaBtn: "ליה, זה בשבילך ✨",
      heroPunchline: "פאנצ'ים שיכלתי לזרוק ואהבה שיכלתי לקבל.",
      heroSub: "בלי אלגוריתמים מזויפים ובלי גינוני אינסטגרם. מקום שקט, כן וציני לפרוק חרדות, לדבר על החיים ולצחוק על הכל.",
      btnVault: "לכל הסרטונים",
      btnOracle: "התייעצי בפאנצ'ומטר",
      statTiktok: "בטיקטוק",
      statLikes: "לייקים",
      statIg: "באינסטגרם",
      statPeace: "רעשי רקע",
      storiesTitle: "הלור של ליה: מאיפה הכל התחיל?",
      storiesSubtitle: "הסיפורים, הבדיחות הפנימיות והטראומות שעיצבו את האישיות הכי לא מתנצלת ברשת.",
      vaultTitle: "כספת הסרטונים והרנטים",
      vaultSubtitle: "כל הלהיטים הוויראליים, ההתמוטטויות העצביות והתובנות החברתיות שנשמרו.",
      filterAll: "הכל (12)",
      filterDark: "הומור שחור",
      filterDating: "דייטים וגברים",
      filterRant: "רנטים ודעות",
      filterLifestyle: "כאוס וחיים",
      oracleTitle: "הפאנצ'ומטר: מוקד ייעוץ אכזרי",
      oracleSubtitle: "תקועה עם דילמה בחיים? החרדה קפצה לבקר? קבלי מנת ציניות מנחמת מליה.",
      oraclePlaceholder: "כתבי בעיה (למשל: הבחור לא עונה 8 שעות, מה לעשות?)",
      oracleBtn: "תני לי פאנץ' 💥",
      oracleSanityBtn: "שחררי את הלסת 🛟",
      oracleCopied: "הועתק ללוח!",
      clubhouseTitle: "המועדון: הצביעו לאתר הבא של ליה",
      clubhouseSubtitle: "ליה שאלה איזה אתר לבנות. הצביעו לפיצ'ר המועדף עליכם או זרקו וידוי אנונימי.",
      voteBtn: "הצביעו",
      votedText: "הצבעתם ✓",
      pitchPlaceholder: "יש לך רעיון אחר לאתר של ליה? כתבי כאן...",
      pitchSubmitBtn: "שלחי הצעה לליה",
      confessTitle: "וידויים אנונימיים",
      confessPlaceholder: "שתפי סיפור מביך או תלונה על החיים בלי שמות...",
      confessAuthorPlaceholder: "כינוי (או השאירי ריק לאנונימי)",
      confessSubmitBtn: "שגרי לריק",
      footerCredits: "נבנה באהבה, כבוד והמון ציניות עבור @not.liya. הבית האינטימי של הקהילה.",
      soundOn: "סאונד פעיל",
      soundOff: "השתק",
      openInIg: "צפי בריל המקורי באינסטגרם",
      modalClose: "סגור (Esc)"
    },
    en: {
      siteTitle: "Liya • notliya.com | The Clubhouse",
      navLore: "The Story",
      navVault: "The Reels",
      navOracle: "The Oracle",
      navClubhouse: "Clubhouse",
      statusText: "Online & judging with love",
      forLiyaBtn: "Hey Liya, this is for you ✨",
      heroPunchline: "Punchlines I could have thrown and love I could have received.",
      heroSub: "No fake global algorithms, no PR facade. A quiet, honest, cynical corner to unpack anxiety, laugh at life, and roast reality.",
      btnVault: "Watch The Reels",
      btnOracle: "Consult The Oracle",
      statTiktok: "on TikTok",
      statLikes: "Likes",
      statIg: "on Instagram",
      statPeace: "Background Noise",
      storiesTitle: "The Lore: How Did We Get Here?",
      storiesSubtitle: "The inside jokes, core memories, and traumas that forged the internet's favorite realist.",
      vaultTitle: "The Rant Vault & Video Archive",
      vaultSubtitle: "Every viral hit, existential breakdown, and unvarnished social observation.",
      filterAll: "All (12)",
      filterDark: "Dark Humor",
      filterDating: "Dating & Men",
      filterRant: "Rants & Takes",
      filterLifestyle: "Chaos & Life",
      oracleTitle: "The Cynic Oracle & Reality Check",
      oracleSubtitle: "Stuck with a dilemma? Existential dread paying a visit? Hit the button for perspective.",
      oraclePlaceholder: "Type your dilemma (e.g., He left me on read for 8 hours...)",
      oracleBtn: "Roast My Dilemma 💥",
      oracleSanityBtn: "Unclench Your Jaw 🛟",
      oracleCopied: "Copied to clipboard!",
      clubhouseTitle: "The Clubhouse: Shape Liya's Permanent Site",
      clubhouseSubtitle: "Liya asked her followers what site to build. Vote for your favorite feature or drop a confession.",
      voteBtn: "Vote",
      votedText: "Voted ✓",
      pitchPlaceholder: "Got another brilliant concept for Liya? Pitch it here...",
      pitchSubmitBtn: "Send Pitch to Liya",
      confessTitle: "Anonymous Confessions",
      confessPlaceholder: "Share an awkward story or grievance anonymously...",
      confessAuthorPlaceholder: "Nickname (or leave blank for Anon)",
      confessSubmitBtn: "Drop into the Void",
      footerCredits: "Crafted with dark humor, affection, and respect for @not.liya following her community call.",
      soundOn: "Sound On",
      soundOff: "Muted",
      openInIg: "Open Original Reel on Instagram",
      modalClose: "Close (Esc)"
    }
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = SITE_DATA;
}
